### PR TITLE
Update libs and site data

### PR DESCRIPTION
**Pull request by oldewyrm**

### CODE REVIEW

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
`data/README.md` being overwritten with a copy of the root README(?) doesn't look quite right

**Comment by TheGiddyLimit** [comment]
`data/changelog.json` looks to have been overwritten with the 5etools changelog (if this is the fault of a scripted copy, then, that script will need fixed too)

is `data/monsterfeatures.json` used? If not, why has it been added?

**Comment by oldewyrm** [comment]
Got a little over-zealous in my copying. No script to speak of, but that's not a bad idea to add in the future.

**Review by TheGiddyLimit — APPROVED** [review]
Fair enough. I believe there _is_ a script to auto-copy existing files; [node/get-data.js](https://github.com/TheGiddyLimit/betterR20/tree/development/node/get-data.js)

**Pull request merged**
